apiVersion: v1
kind: Service
metadata:
  name: gitlab-dashboard-service
  labels:
    app: gitlab-dashboard
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: gitlab-dashboard
